# Generated by Django 4.2.7 on 2023-11-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
